---
- name: Update klipper config
  hosts: ender2pro
  remote_user: root
  gather_facts: no

  tasks:
  - name: Copy printer.cfg to printer
    ansible.builtin.copy:
      src: ./printer.cfg
      dest: /home/pi/klipper_config/printer.cfg
      owner: pi
      group: pi
    register: printer_config

  - name: Copy webcam.txt to printer
    ansible.builtin.copy:
      src: ./webcam.txt
      dest: /home/pi/klipper_config/webcam.txt
      owner: pi
      group: pi
    register: webcam_config

  - name: Delete old macros.cfg file
    ansible.builtin.file:
      path: /home/pi/klipper_config/macros.cfg
      state: absent
      force: yes

  - name: Create macros folder
    ansible.builtin.file:
      path: /home/pi/klipper_config/macros
      state: directory
      force: yes

  - name: Synchronize macros folder
    ansible.posix.synchronize:
      src: macros/
      dest: /home/pi/klipper_config/macros/
      delete: yes
      rsync_opts:
        - --include=*.cfg
        - --delete-excluded
      #  - --delete
      #  - --delete-excluded
    register: macros_config

  - name: Klipper Service
    service:
      name: klipper
      state: restarted
    when: 
    - printer_config.changed or macros_config.changed

  - name: Webcamd Service
    service:
      name: webcamd
      state: restarted
    when: 
    - webcam_config.changed
